### ISSUE TITLE
FirRock API ERROR

### ISSUE THREAD

**Issue by Crabbit-F** [bxiaoj/video-parser#4]
I got 500 when request 'http://vproctol.zeed.ink/api/v1/dy/getUserVideos',and the same response i got by try online api test from 'http://vproctol.zeed.ink/api/v1/apidoc/#api-DouYin-getUserVideos'.Can you get 200 today?Thanks.

{"code":500,"msg":"fail","error":null,"request_id":"20230812150412218mPEdzY1W"}

**Comment by bxiaoj** [comment]
Please try posting your request parameters or consult the author of FireRock

**Comment by mamasexeno** [comment]
same {"code":500,"msg":"get user videos Error","error":"Request failed with status code 500"}
http://localhost:3000/api/dy/getUserVideos?sec_uid=MS4wLjABAAAAj1X8oOFYWShV87Pq6s9uXR7v3jkr0KH2PIJQAKKJFXQ&count=2&max_cursor=0

**Comment by bxiaoj** [comment]
Bug had fix by FirRock,  please try again.
